# Stage 1: Serve with Nginx (không build)
FROM nginx:1.27.5

# Copy build output from host to Nginx html directory
COPY build/ /usr/share/nginx/html

# Copy custom Nginx configuration
COPY default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80