name: Deploy to EC2

on:
  push:
    branches:
      - main  # Chạy khi push vào branch main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Máy ảo GitHub Actions chạy trên Ubuntu
    steps:
      # Bước 1: Lấy code từ GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Đảm bảo phiên bản Node.js phù hợp
          cache: 'npm'  # Cache để tăng tốc cài đặt

      # Bước 3: Kiểm tra phiên bản Node.js
      - name: Check Node.js version
        run: node -v

      # Bước 4: Cài đặt dependencies và build dự án
      - name: Install dependencies and build
        run: |
          npm install
          CI=false npm run build  # Bỏ qua lỗi CI để build thành công

      # Bước 5: Kết nối và deploy lên EC2
      - name: Deploy to EC2
        env:
          EC2_HOST: 174.129.56.237  # IP của EC2
          EC2_USER: ec2-user  # User SSH của EC2
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}  # Private key SSH từ GitHub Secrets
        run: |
          # Tạo file SSH Key
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem  # Đảm bảo quyền chính xác

          # Thêm EC2 vào known_hosts để tránh lỗi "Host key verification failed"
          mkdir -p ~/.ssh
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

          # Dùng rsync để đồng bộ file build nhanh hơn scp
          rsync -avz -e "ssh -i key.pem" ./build/ $EC2_USER@$EC2_HOST:/home/$EC2_USER/

          # SSH vào EC2 để di chuyển file vào thư mục Nginx và reload service
          ssh -i key.pem $EC2_USER@$EC2_HOST << EOF
            sudo rsync -avz /home/$EC2_USER/ /usr/share/nginx/html/
            sudo systemctl reload nginx
          EOF

          # Xóa file key sau khi xong
          rm -f key.pem
