name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Hoặc phiên bản bạn dùng

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to EC2
        env:
          EC2_HOST: 3.90.5.217
          EC2_USER: ec2-user
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 400 key.pem
          
          # Dùng rsync với tùy chọn SSH bỏ qua host key checking
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./build/ $EC2_USER@$EC2_HOST:/home/$EC2_USER/
          
          # SSH với tùy chọn bỏ qua host key checking
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
            sudo rsync -avz /home/$EC2_USER/ /usr/share/nginx/html/
            sudo systemctl reload nginx
          EOF
          
          rm key.pem
