# name: Deploy Fullstack to EC2

# on:
#   push:
#     branches:
#       - main  # Mỗi khi push lên nhánh main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       # 1. Checkout code
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # 2. Copy FRONTEND source code lên EC2
#       - name: Copy FRONTEND source code to EC2
#         uses: appleboy/scp-action@master
#         with:
#           host: 13.57.34.159
#           username: ec2-user
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "src/"
#           target: "/home/ec2-user/"

#       # 3. Copy BACKEND source code lên EC2
#       - name: Copy BACKEND source code to EC2
#         uses: appleboy/scp-action@master
#         with:
#           host: 13.57.34.159
#           username: ec2-user
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "backend/"
#           target: "/home/ec2-user/"

#       # 4. Cài Node.js trên EC2 (nếu chưa cài)
#       - name: Install Node.js & npm on EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: 13.57.34.159
#           username: ec2-user
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             # Cài Node.js 18.x
#             curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
#             sudo yum install -y nodejs
#             node -v
#             npm -v

#       # 5. Build FRONTEND trên EC2
#       - name: Build frontend on EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: 13.57.34.159
#           username: ec2-user
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           # timeout: 1800
#           script: |
#             cd /home/ec2-user
#             npm install
#             npm run build
#             ls -lah build/

#       # 6. Deploy FRONTEND build sang /var/www/html (hoặc folder tuỳ ý)
#       # - name: Deploy build to Apache
#       #   uses: appleboy/ssh-action@master
#       #   with:
#       #     host: ${{ secrets.EC2_HOST }}
#       #     username: ${{ secrets.EC2_USER }}
#       #     key: ${{ secrets.SSH_PRIVATE_KEY }}
#       #     script: |
#       #       sudo rm -rf /var/www/html/*
#       #       sudo cp -r /home/ec2-user/frontend/build/* /var/www/html/
#       #       sudo chown -R apache:apache /var/www/html
#       #       sudo chmod -R 755 /var/www/html
#       #       sudo systemctl restart httpd
#       - name: Deploy build to Nginx
#         uses: appleboy/ssh-action@master
#         with:
#           host: 13.57.34.159
#           username: ec2-user
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             sudo rm -rf /usr/share/nginx/html/*
#             sudo cp -r /home/ec2-user//build/* /usr/share/nginx/html/
#             sudo chown -R nginx:nginx /usr/share/nginx/html
#             sudo chmod -R 755 /usr/share/nginx/html
#             sudo systemctl restart nginx
    
#       # 7. Cài đặt Backend dependencies & run
#       - name: Deploy backend on EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: 13.57.34.159
#           username: ec2-user
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd /home/ec2-user/backend
#             npm install

#             # Bạn có thể build nếu có step build (TypeScript, Babel, v.v.), ví dụ:
#             # npm run build

#             # Dùng pm2 để chạy server (đảm bảo pm2 đã được cài)
#             sudo npm install -g pm2
#             pm2 stop my-backend || true
#             pm2 delete my-backend || true
#             pm2 start ./src/app.js --name my-backend --watch

#             # Kiểm tra pm2 status
#             pm2 status

name: Deploy Fullstack to EC2

on:
  push:
    branches:
      - main  # Mỗi khi push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Copy FRONTEND source code lên EC2
      # Frontend nằm ở thư mục gốc của repo, copy toàn bộ trừ thư mục backend
      - name: Copy FRONTEND source code to EC2
        uses: appleboy/scp-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./" # Copy toàn bộ thư mục gốc của repo
          # Loại trừ thư mục backend và .github
          exclude: ".github/, backend/"
          target: "/home/ec2-user/frontend_app/" # Đặt vào một thư mục riêng biệt cho frontend trên EC2

      # 3. Copy BACKEND source code lên EC2
      - name: Copy BACKEND source code to EC2
        uses: appleboy/scp-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/" # Copy thư mục backend từ repo
          target: "/home/ec2-user/" # Đặt vào /home/ec2-user/backend/ trên EC2

      # 4. Cài Node.js trên EC2 (nếu chưa cài)
      - name: Install Node.js & npm on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Cài Node.js 18.x nếu chưa có
            if ! command -v node &> /dev/null
            then
                echo "Node.js not found, installing..."
                curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
                sudo yum install -y nodejs
                node -v
                npm -v
            else
                echo "Node.js already installed."
            fi
            
            # Cài pm2 nếu chưa có
            if ! command -v pm2 &> /dev/null
            then
                echo "pm2 not found, installing..."
                sudo npm install -g pm2
            else
                echo "pm2 already installed."
            fi

      # 5. Build FRONTEND trên EC2
      - name: Build frontend on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Di chuyển vào thư mục gốc của frontend app trên EC2
            cd /home/ec2-user/frontend_app
            echo "Current directory after cd: $(pwd)"
            echo "Listing contents of current directory:"
            ls -lah
            
            # Cài đặt dependencies cho frontend
            npm install
            
            # Build frontend
            npm run build
            echo "Listing contents of build directory:"
            ls -lah build/

      # 6. Deploy FRONTEND build sang /usr/share/nginx/html (cho Nginx)
      - name: Deploy build to Nginx
        uses: appleboy/ssh-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Attempting to deploy frontend build to Nginx..."
            # Xóa các file cũ trong thư mục phục vụ của Nginx
            sudo rm -rf /usr/share/nginx/html/*
            # Copy các file build mới
            sudo cp -r /home/ec2-user/frontend_app/build/* /usr/share/nginx/html/
            # Đặt quyền sở hữu và quyền truy cập cho Nginx
            sudo chown -R nginx:nginx /usr/share/nginx/html
            sudo chmod -R 755 /usr/share/nginx/html
            # Khởi động lại Nginx
            sudo systemctl restart nginx
            echo "Frontend deployment to Nginx completed."
    
      # 7. Cài đặt Backend dependencies & run
      - name: Deploy backend on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Starting backend deployment..."
            # Di chuyển vào thư mục backend
            cd /home/ec2-user/backend
            echo "Current directory after cd: $(pwd)"
            echo "Listing contents of current directory:"
            ls -lah
            
            # Cài đặt dependencies cho backend
            npm install

            # Dùng pm2 để chạy server (đảm bảo pm2 đã được cài ở bước 4)
            echo "Stopping and deleting existing pm2 process if any..."
            pm2 stop my-backend || true
            pm2 delete my-backend || true
            
            echo "Starting backend with pm2..."
            # Chú ý: pm2 sẽ tìm server.js (file main của backend)
            # Dựa vào package.json backend, main là index.js nhưng script dev lại là server.js
            # "main": "index.js",
            # "scripts": { "dev": "nodemon server.js" }
            # Bạn cần đảm bảo pm2 chạy đúng file khởi động backend.
            # Dựa vào server.js, nó là entry point của bạn.
            pm2 start server.js --name my-backend --watch
            
            # Kiểm tra pm2 status
            echo "pm2 status:"
            pm2 status
            echo "Backend deployment completed."